server:
  port: 9091

spring:
  application:
    name: Product Microservice
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shopping

product:
  currencies:
    - INR
    - USD
    - EUR