server:
  port: 9091

spring:
  application:
    name: Product Microservice
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shopping
  profiles:
    active: local

logging:
  file:
    name: d:\logs\product.log
#    path: d:\logs  #spring.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
#  level:
#    root: INFO

# actuator specific

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: ALWAYS
  health:
    mongo:
      enabled: true

info:
  app:
    name: Product Microservice
    version: 1.0
    desccription: Add and retrieve product information

product:
  currencies:
    - INR
    - USD
    - EUR

---
spring:
  config:
    activate:
      on-profile:
        - local
  application:
    name: Product Microservice(Local Env)


